"use strict";
var num1 = 5;
var num2 = 9;
console.log("num1的值是：" + num1);
console.log("num2的值是：" + num2);
var res5 = num1 > num2;
console.log("num1 > num2的结果是：" + res5);
var res6 = num1 < num2;
console.log("num1 < num2的结果是：" + res6);
var res7 = num1 >= num2;
console.log("num1 >= num2的结果是：" + res7);
var res8 = num1 <= num2;
console.log("num1 <= num2的结果是：" + res8);
var res9 = num1 == num2;
console.log("num1 == num2的结果是：" + res9);
var res10 = num1 != num2;
console.log("num1 != num2的结果是：" + res10);
